# Generated by Django 5.0.7 on 2024-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=20)),
                ("pic", models.ImageField(upload_to="media")),
                ("caption", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
