# Generated by Django 5.0.7 on 2024-08-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_post_uname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="uname",
            new_name="user_obj",
        ),
    ]
